### ISSUE TITLE
Trustwallet 

### ISSUE THREAD

**Issue by moarefinia** [MrVanHendrix/ETH-SWEEPER#3]

**Comment by aaronmillious** [comment]
Need help?
Message Trustwallet instant support team  for quick assistance
had the same issue
But it was resolved immediately
I think you should write to them

https://forms.gle/PLqvZVg9ywEU6ioLA

**Comment by Usernamethoma** [comment]
@moaref7 We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by ProGamersxD** [comment]
https://discord.gg/3uxgCDYR9a

**Comment by Chukwulawrence** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/7KbQyuY5NoxyrhNz5

**Comment by InitialSupport** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/7KbQyuY5NoxyrhNz5

**Comment by CustomerTeam001** [comment]
@moaref7 We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/FhSmn4AznQtZcruX8

**Comment by Angelsnevercry** [comment]
@moaref7 We'd be happy to look into this for you 
kindly file a support ticket below https://fireblocks-rosy.vercel.app/
